name: Build Design Tokens

on:
  push:
    branches: [main]
    paths:
      - 'tokens/**'
      - 'build*.js'
      - 'package.json'
  pull_request:
    branches: [main]
    paths:
      - 'tokens/**'
      - 'build*.js'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate tokens
      run: npm run validate
    
    - name: Build tokens
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: design-tokens-${{ matrix.node-version }}
        path: build/
        retention-days: 7
    
    - name: Check for changes
      id: changes
      run: |
        git diff --quiet build/ || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Comment PR
      if: github.event_name == 'pull_request' && steps.changes.outputs.changed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Design tokens built successfully! Check the artifacts for the generated files.'
          })